# Generated by Django 3.0.14 on 2022-01-06 11:17

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_missing_roles'),
        ('insuree', '0012_policyrenewaldetail'),
        ('location', '0006_users_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='HFBankDetails',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='SchemeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='SPBankUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('DFSP', models.CharField(db_column='DFSP', max_length=255)),
                ('HFAccountNumber', models.CharField(db_column='AccountNumber', max_length=255)),
                ('HFAccountName', models.CharField(db_column='AccountName', max_length=255)),
                ('healthFacility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.HealthFacility')),
            ],
            options={
                'db_table': 'tblHFBankDetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsureeBankDetails',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='SchemeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='InsureeBankDetailsUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('DFSP', models.CharField(db_column='DFSP', max_length=255)),
                ('InsureeAccountNumber', models.CharField(db_column='AccountNumber', max_length=255)),
                ('InsureeAccountName', models.CharField(db_column='AccountName', max_length=255)),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insuree.Insuree')),
            ],
            options={
                'db_table': 'tblInsureeBankDetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Healthfacilityy',
            fields=[
            ],
            options={
                'db_table': 'tblHealthFacility',
                'ordering': ('id',),
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('location.healthfacility',),
        ),
        migrations.CreateModel(
            name='insuree',
            fields=[
            ],
            options={
                'db_table': 'tblInsuree',
                'ordering': ('id',),
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insuree.insuree',),
        ),
        migrations.CreateModel(
            name='InsureeBankDetailsMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insureeBankDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='financialInstitution.InsureeBankDetails')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insureeBankDetails', to='core.MutationLog')),
            ],
            options={
                'db_table': 'InsureeBankDetailsMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.CreateModel(
            name='HFBankDetailsMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hFBankDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='financialInstitution.HFBankDetails')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hFBankDetails', to='core.MutationLog')),
            ],
            options={
                'db_table': 'HFBankDetailsMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
